apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-api
  namespace: max-weather-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      containers:
        - name: backend-api
          image: quyencl91/max-weather:2abe699fb6f5eeb1ebad258186b942991763820e
          ports:
            - containerPort: 80
              name: backend-api
          resources:
            requests:
              cpu: 256m
              memory: 512Mi
            limits:
              cpu: 512m
              memory: 1024Mi
