apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-api
  namespace: blooperry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      imagePullSecrets:
        - name: dockerhubpull
      containers:
        - name: backend-api
          image: ptd0409/td-argocd:main
          ports:
            - containerPort: 8086
              name: backend-api
          resources:
            requests:
              cpu: 256m
              memory: 512Mi
            limits:
              cpu: 512m
              memory: 1024Mi
