apiVersion: v1
kind: Namespace
metadata:
  name: max-weather-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-api
  namespace: max-weather-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      containers:
        - name: backend-api
          image: nginx:latest
          ports:
            - containerPort: 80
              name: backend-api
          resources:
            requests:
              cpu: 256m
              memory: 512Mi
            limits:
              cpu: 512m
              memory: 1024Mi
---
apiVersion: v1
kind: Service
metadata:
  name: svc-backend-api
  namespace: max-weather-dev
spec:
  ports:
    - port: 80 #egress port
      targetPort: 80 #ingress port ~ containerPort
  selector:
    app: backend-api
  type: ClusterIP
