name: Build, Push and Deploy to Kubernetes

on:
  push:
    branches:
      - main # Trigger action on pushes to main branch
    paths-ignore:
      - "app.api/k8s/**"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -f app.api/app.dockerfile  -t ptd0409/td-argocd:${{ github.ref_name }} .

      - name: Push Docker image to Docker hub
        run: |
          docker push ptd0409/td-argocd:${{ github.ref_name }}

  update_deployment:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update the deployment manifest file
        run: |
          cd app.api/k8s
          git config user.name "ptd0409"
          git config user.email "leonardcurryst@gmail.com"
          kustomize edit set image ptd0409/td-argocd:${{ github.ref_name }}
          cat kustomization.yaml
          cd ../..
          git pull 
          git add .
          git commit -am "Update image to ${{ github.ref_name }}"
          git push https://x-access-token:${{ secrets.GH_ACTION_PAT }}@github.com/ptd0409/ArgoCD.git
